import {createHeldReadGate} from '../held-read-gate.mjs';
const gates=createHeldReadGate();
import http from 'node:http';import{evidencePayload}from'../run-evidence/fixtures.mjs';
const calls=[],at='2026-01-01T00:00:00.000Z';
const observed=value=>({status:'recorded',source:'run_metadata',verification:'stored_observation',value});
http.createServer((req,res)=>{const u=new URL(req.url,'http://fixture');if(gates.control(req,res,u))return;res.setHeader('content-type','application/json');res.setHeader('cache-control','no-store');if(u.pathname==='/health'){res.end('{}');return;}if(u.pathname==='/__calls'){res.end(JSON.stringify(calls));return;}calls.push({method:req.method,path:u.pathname,id:u.searchParams.get('runId')});if(req.method!=='GET'){res.statusCode=405;res.end('{}');return;}const id=u.searchParams.get('runId');if(u.pathname==='/batch/replay/runs'){const send=()=>res.end(JSON.stringify(evidencePayload(id)));if(!gates.hold(u,res,send))send();return;}if(u.pathname!=='/batch/replay/runs/provenance'){res.end('{}');return;}if(id==='offline'){res.statusCode=503;res.end('{}');return;}
const raw={mode:'paper_only',readOnly:true,contractVersion:'replay_provenance_read.v1',requestedRunId:id,status:['missing','blocked','limit','ambiguous'].includes(id)?id:'partial',comparability:'unavailable',clone:'unavailable',fields:{'window.source':observed('explicit'),'window.startAt':observed(at),'window.endAt':observed('2026-02-01T00:00:00.000Z'),'window.timezoneOffsetMinutes':observed(540),'configuration.initialCashKrw':observed(0),'configuration.executionPolicy.allowFractionalShares':observed(false),'research.configHash':{...observed('sha256:'+'1'.repeat(64)),source:'research_manifest'},'batch.seed':{status:'unavailable',reason:'redacted_text',value:null},'requestedConfig':{status:'unavailable',reason:'not_persisted',value:null},'runtime.nodeVersion':{status:'unavailable',reason:'not_persisted',value:null}}};
raw.fields['configuration.packetExpiresInSeconds']=observed(120);raw.fields['configuration.maxCandidates']=observed(20);raw.fields['configuration.maxSnapshotAgeSeconds']=observed(0);if(id==='omitted_v1')delete raw.fields['configuration.initialCashKrw'];if(id==='absent_stored')raw.fields['configuration.initialCashKrw']={status:'unavailable',reason:'not_present',value:null};
if(id==='wrong_child')raw.requestedRunId='other_child';if(id==='unsafe_date')for(const key of ['window.startAt','window.endAt','window.rangeStart','window.rangeEnd','configuration.clock.startAt','configuration.clock.endAt'])raw.fields[key]=observed('2026-01-01 (/home/SYNTHETIC_PRIVATE/token.txt)');
if(id.startsWith('fixture_held_')){raw.fields['configuration.initialCashKrw']=observed(99);raw.fields['research.configHash']={...observed('sha256:'+'2'.repeat(64)),source:'research_manifest'};}const send=()=>res.end(JSON.stringify(raw));if(!gates.hold(u,res,send))send();}).listen(8796,'127.0.0.1');
