import {heldComparisonNavigation} from '../held-comparison-navigation';
import{test,expect}from'@playwright/test';import path from'node:path';import{createRequire}from'node:module';const require=createRequire(path.join(__dirname,'package.json'));
const compare=(candidate='candidate')=>'/dashboard/experiments/compare?baseline=child&candidate='+candidate;
test('exact detail exposes collapsible stored conditions, zero, false and unverified hash',async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('/dashboard/lab/runs/child');await expect(page).toHaveTitle(/dashboard|Toss|Trading/i);const panel=page.getByTestId('run-provenance');await expect(panel).toContainText('일부 저장 관측');await expect(page.getByRole('heading',{name:'Run Detail',exact:true})).toBeVisible();if(process.env.PROVENANCE_UI_ARTIFACTS)await page.screenshot({path:path.join(process.env.PROVENANCE_UI_ARTIFACTS,`provenance-first-${info.project.name}.png`),fullPage:false});await expect(panel).toContainText('일부 저장 관측');await expect(panel).toContainText('현재 자료·코드·정책과 대조 검증하지 않았어요');await panel.scrollIntoViewIfNeeded();if(process.env.PROVENANCE_UI_ARTIFACTS)await page.screenshot({path:path.join(process.env.PROVENANCE_UI_ARTIFACTS,`provenance-collapsed-${info.project.name}.png`),fullPage:false});await panel.getByText('실행 설정',{exact:true}).click();await expect(panel.locator('dt').filter({hasText:'configuration.initialCashKrw'})).toBeVisible();await expect(panel).toContainText('저장 관측 · 실행 metadata');await panel.getByText('비용·체결',{exact:true}).click();await expect(panel).toContainText('false');await panel.getByText('저장 hash',{exact:true}).click();await expect(panel).toContainText('sha256:'+'1'.repeat(64));await expect(panel).toContainText('현재 자료와 미검증');await panel.getByText('복원되지 않은 입력·runtime',{exact:true}).click();await expect(panel).toContainText('저장되지 않음');await expect(panel).not.toContainText(/SYNTHETIC_PRIVATE|token\.txt/);
  await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const axe=(window as unknown as{axe:{run:(node:Element,opts:unknown)=>Promise<{violations:unknown[]}>}}).axe;return(await axe.run(document.querySelector('main')!,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations;});expect(violations).toEqual([]);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(process.env.PROVENANCE_UI_ARTIFACTS)await page.screenshot({path:path.join(process.env.PROVENANCE_UI_ARTIFACTS,`provenance-detail-${info.project.name}.png`),fullPage:true});
});
test('compare keeps per-column conditions isolated and clone disabled',async({page},info)=>{await page.goto(compare());const a=page.getByTestId('comparison-baseline'),b=page.getByTestId('comparison-candidate');await expect(a.getByTestId('run-provenance')).toContainText('child');await expect(b.getByTestId('run-provenance')).toContainText('candidate');await expect(page.getByRole('button',{name:'입력 복제 사용 불가'})).toBeDisabled();await a.getByTestId('run-provenance').scrollIntoViewIfNeeded();await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>{const axe=(window as unknown as{axe:{run:(node:Element,opts:unknown)=>Promise<{violations:unknown[]}>}}).axe;return(await axe.run(document.querySelector('main')!,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations;});expect(violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(process.env.PROVENANCE_UI_ARTIFACTS)await page.screenshot({path:path.join(process.env.PROVENANCE_UI_ARTIFACTS,`provenance-compare-${info.project.name}.png`),fullPage:true});for(const[id,label]of[['offline','조회 연결 불가'],['missing','저장 조건 미관측'],['blocked','조회 차단'],['limit','조회 한도 도달'],['ambiguous','중복 실행 ID'],['wrong_child','응답 확인 필요']]){await page.goto(compare(id));await expect(page.getByTestId('comparison-baseline').getByTestId('run-provenance')).toContainText('일부 저장 관측');const panel=page.getByTestId('comparison-candidate').getByTestId('run-provenance');await expect(panel).toContainText(label);await expect(panel.locator('details')).toHaveCount(0);}});
test('unsafe dates remain unavailable without exposing personal path in either surface',async({page})=>{for(const route of ['/dashboard/lab/runs/unsafe_date',compare('unsafe_date')]){await page.goto(route);const panel=page.getByTestId('run-provenance').last();await panel.getByText('관측 기간',{exact:true}).click();await expect(panel).toContainText('값 확인 불가');await expect(page.getByRole('main')).not.toContainText(/SYNTHETIC_PRIVATE|token\.txt|\/home\//);}});
test('keyboard disclosure, exact URL, Back/reload and GET-only requests preserve identity',async({page,request})=>{await page.goto(compare());const panel=page.getByTestId('comparison-baseline').getByTestId('run-provenance'),summary=panel.locator('summary').first();await expect(summary).toBeVisible();await summary.focus();await expect(summary).toBeFocused();await summary.press('Enter');await expect(panel.locator('details').first()).toHaveAttribute('open','');await page.getByTestId('comparison-baseline').getByRole('link',{name:'이 실행 상세 보기'}).click();await expect(page).toHaveURL(/\/dashboard\/lab\/runs\/child$/);await expect(page.getByTestId('run-provenance')).toContainText('child');await page.goBack();await expect(page).toHaveURL(/baseline=child&candidate=candidate$/);await page.reload();await expect(page.getByTestId('comparison-candidate').getByTestId('run-provenance')).toContainText('candidate');const calls=await(await request.get('http://127.0.0.1:8796/__calls')).json();expect(calls.every((c:{method:string})=>c.method==='GET')).toBe(true);});

test('new exact pair survives old runs and provenance responses from one held generation',async({page,request},info)=>{await heldComparisonNavigation(page,request,{api:'http://127.0.0.1:8796',project:info.project.name,baseline:'child',candidate:'candidate',provenance:true});});
