import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import {evidenceArtifacts,evidencePayload} from './run-evidence/fixtures.mjs';
const source=await readFile(new URL('../src/lib/runEvidence.ts',import.meta.url),'utf8');
const evidenceUrl='data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(source));
const {buildRunEvidence,evidenceReference,evidenceReferences,readEvidenceSelection,isRunEvidence}=await import(evidenceUrl);
const make=(scenario='normal')=>buildRunEvidence(evidenceArtifacts('child',scenario),'child');
const row=(view,kind)=>view.buckets.find(b=>b.kind===kind).rows[0];
test('an invalid same-child record cannot erase a duplicate identity',()=>{const raw=evidenceArtifacts('child');raw.trades.push({...raw.trades[0],quantity:-1});raw.tradeCount=2;raw.totalTradeCount=2;const view=buildRunEvidence(raw,'child');assert.equal(view.buckets[3].invalid,1);assert.equal(view.buckets[3].duplicates,1);assert.equal(evidenceReference(view,'trade','trade_1').state,'ambiguous');assert.equal(isRunEvidence(view,'child'),true);});
test('exact child projection retains explicit packet and trade-to-Risk references',()=>{const view=make();assert.equal(view.source,'bound');assert.equal(isRunEvidence(view,'child'),true);assert.equal(evidenceReference(view,'packet','packet_1').state,'linked');assert.deepEqual(evidenceReferences(view,row(view,'trade')).map(r=>[r.kind,r.id,r.state]),[['packet','packet_1','linked'],['risk','risk_1','linked']]);assert.equal(row(view,'decision').at,null);});
test('different child and blocked artifacts cannot supply selectable records',()=>{for(const scenario of ['mismatch','blocked']){const view=make(scenario);assert.equal(view.source,scenario==='mismatch'?'mismatch':'blocked');assert.equal(view.buckets.flatMap(b=>b.rows).length,0);assert.equal(evidenceReference(view,'packet','packet_1').state,'unavailable');}});
test('per-record wrong-run and display-schema failures are separate diagnostics',()=>{for(const [scenario,field]of [['wrong_run','wrongRun'],['bad','invalid']]){const view=make(scenario);for(const bucket of view.buckets){assert.equal(bucket[field],1);assert.equal(bucket.rows.length,0);}}});
test('duplicate IDs in every collection are ambiguous rather than first-or-last wins',()=>{const view=make('duplicate');for(const bucket of view.buckets){assert.equal(bucket.duplicates,1);assert.ok(bucket.rows.every(r=>r.duplicate));assert.equal(evidenceReference(view,bucket.kind,bucket.rows[0].id).state,'ambiguous');}});
test('missing reference and absent target outside truncated range stay distinct',()=>{assert.equal(evidenceReferences(make('missing'),row(make('missing'),'trade'))[1].state,'missing');assert.equal(evidenceReferences(make('truncated'),row(make('truncated'),'trade'))[1].state,'outside_loaded_range');assert.ok(make('truncated').buckets.every(b=>b.truncated));});
test('explicit Risk reference crossing Packet identity is blocked',()=>{const view=make('cross_packet');assert.equal(evidenceReferences(view,row(view,'trade'))[1].state,'mismatch');});
test('source order is retained while reversed and equal timestamps are diagnosed',()=>{const view=make('out_of_order'),bucket=view.buckets[0];assert.equal(bucket.outOfOrder,true);assert.deepEqual(bucket.rows.map(r=>r.id),['packet_1','packet_2']);assert.equal(make('same_time').buckets[0].sameTime,true);});
test('genuine empty arrays differ from corrupt and degraded reads',()=>{assert.ok(make('empty').buckets.every(b=>b.status==='ok'&&b.returned===0&&b.rows.length===0));assert.ok(make('corrupt').buckets.every(b=>b.status==='corrupt'&&b.rows.length===0));assert.ok(make('degraded').buckets.every(b=>b.status==='degraded'&&b.corrupt===1&&b.rows.length===1));});
test('projection never forwards extra raw output, paths or credential fields',()=>{const raw=evidenceArtifacts('child');raw.packets[0].secret='DO_NOT_FORWARD';raw.decisions[0].command='DO_NOT_FORWARD';raw.trades[0].outputPath='DO_NOT_FORWARD';assert.doesNotMatch(JSON.stringify(buildRunEvidence(raw,'child')),/DO_NOT_FORWARD/);});
test('inconsistent counts, oversized arrays and invalid statuses fail closed per collection',()=>{for(const mutate of [raw=>raw.packetCount=2,raw=>raw.totalPacketCount=0,raw=>raw.packetCorruptLineCount=-1,raw=>raw.packetsStatus='invented',raw=>raw.packets=Array(101).fill(raw.packets[0])]){const raw=evidenceArtifacts('child');mutate(raw);const view=buildRunEvidence(raw,'child');assert.equal(view.buckets[0].status,'invalid');assert.equal(view.buckets[0].rows.length,0);}});
test('selection IDs are exact and unsupported choices never become default rows',()=>{assert.deepEqual(readEvidenceSelection('risk:risk_1'),{kind:'risk',id:'risk_1'});for(const input of [null,'unknown:packet_1','packet:','packet:\n','packet:'+ 'x'.repeat(257)])assert.equal(readEvidenceSelection(input),null);assert.equal(evidenceReference(make(),'trade','unknown').state,'missing');});
test('client transport rejects wrong child, invalid row schemas and extra projected fields',()=>{for(const mutate of [v=>v.runId='other',v=>v.buckets[0].rows[0].details.secret='hidden',v=>v.buckets[3].rows[0].details.quantity=-1,v=>v.buckets[0].rows[0].at='invalid',v=>v.buckets[0].status='invented']){const view=make();mutate(view);assert.equal(isRunEvidence(view,'child'),false);}});
async function reader(){const vm=await readFile(new URL('../src/lib/dashboardViewModels.ts',import.meta.url),'utf8');const vmUrl='data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(vm));let s=await readFile(new URL('../src/lib/runEvidenceReader.ts',import.meta.url),'utf8');s=s.replace("'./dashboardViewModels'",JSON.stringify(vmUrl)).replace("'./runEvidence'",JSON.stringify(evidenceUrl));return import('data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(s)));}
test('reader uses one no-store GET for same-child detail and evidence',async t=>{const original=global.fetch,env=process.env.DASHBOARD_OPS_API_BASE_URL;process.env.DASHBOARD_OPS_API_BASE_URL='http://fixture.test';t.after(()=>{global.fetch=original;if(env===undefined)delete process.env.DASHBOARD_OPS_API_BASE_URL;else process.env.DASHBOARD_OPS_API_BASE_URL=env;});const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(evidencePayload('child')),{status:200});};const {readRunWorkspacePageData}=await reader();const result=await readRunWorkspacePageData('child');assert.equal(calls.length,1);assert.equal(calls[0].options.method,'GET');assert.equal(calls[0].options.cache,'no-store');assert.match(calls[0].url,/runId=child$/);assert.equal(result.runDetail.status,'ok');assert.equal(result.evidence.source,'bound');});
test('reader distinguishes invalid/offline without propagating raw exception details',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);const {readRunWorkspacePageData}=await reader();global.fetch=async()=>new Response('{}',{status:200});assert.equal((await readRunWorkspacePageData('child')).runDetail.status,'invalid');global.fetch=async()=>{throw new Error('secret-provider-path');};const result=await readRunWorkspacePageData('child');assert.equal(result.runDetail.status,'offline');assert.doesNotMatch(JSON.stringify(result),/secret-provider-path/);});

test('display money, provider text and Risk rule fields obey their stored schema',()=>{for(const mutate of [r=>r.packets[0].candidates[0].lastPriceKrw=0.5,r=>r.decisions[0].decisions[0].budgetKrw=0.5,r=>r.decisions[0].summary='',r=>r.riskDecisions[0].checkedRules=[''],r=>r.trades[0].priceKrw=0.5,r=>r.trades[0].status='invented']){const raw=evidenceArtifacts('child');mutate(raw);assert.equal(buildRunEvidence(raw,'child').buckets.reduce((sum,b)=>sum+b.invalid,0),1);}});

test('missing record arrays remain regional invalid evidence, not invalid snapshot transport',()=>{const raw=evidenceArtifacts('child');delete raw.packets;const view=buildRunEvidence(raw,'child');assert.equal(view.buckets[0].status,'invalid');assert.equal(view.buckets[0].returned,null);assert.equal(isRunEvidence(view,'child'),true);});
