import assert from 'node:assert/strict';import{test}from'node:test';import{readFile}from'node:fs/promises';import{stripTypeScriptTypes}from'node:module';
const vm='data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(await readFile(new URL('../src/lib/dashboardViewModels.ts',import.meta.url),'utf8')));
const source=(await readFile(new URL('../src/lib/runProvenance.ts',import.meta.url),'utf8')).replace("'./dashboardViewModels'",JSON.stringify(vm));
const{projectRunProvenance,readRunProvenance,strictTimestamp}=await import('data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(source)));
const at='2026-10-04T01:00:00.000Z',recorded=value=>({status:'recorded',source:'run_metadata',verification:'stored_observation',value}),absent=reason=>({status:'unavailable',reason,value:null});
const fixture=()=>({mode:'paper_only',readOnly:true,contractVersion:'replay_provenance_read.v1',requestedRunId:'child',status:'partial',comparability:'unavailable',clone:'unavailable',fields:{'configuration.initialCashKrw':recorded(0),'configuration.executionPolicy.allowFractionalShares':recorded(false),'window.startAt':recorded('2026-01-01T00:00:00.000Z'),'research.configHash':{...recorded('sha256:'+'1'.repeat(64)),source:'research_manifest'},'batch.seed':absent('redacted_text'),'requestedConfig':absent('not_persisted'),'runtime.nodeVersion':absent('not_persisted')}});
const project=raw=>projectRunProvenance(raw,'child',at);
test('packet execution scalars follow backend bounds including zero snapshot age',()=>{
  for(const[key,minimum]of [['configuration.packetExpiresInSeconds',1],['configuration.maxCandidates',1],['configuration.maxSnapshotAgeSeconds',0]]){
    for(const value of [minimum,Number.MAX_SAFE_INTEGER]){const raw=fixture();raw.fields[key]=recorded(value);assert.equal(project(raw).fields[key].value,value);}
    for(const value of [minimum-1,0.5,Number.MAX_SAFE_INTEGER+1,Infinity,null,'10']){const raw=fixture();raw.fields[key]=recorded(value);assert.deepEqual(project(raw).fields[key],absent('invalid'));}
  }
});
test('omitted v1 properties are invalid response fields rather than absent storage observations',()=>{
  const raw=fixture();delete raw.fields['configuration.initialCashKrw'];assert.deepEqual(project(raw).fields['configuration.initialCashKrw'],absent('invalid'));
  raw.fields['configuration.initialCashKrw']=absent('not_present');assert.deepEqual(project(raw).fields['configuration.initialCashKrw'],absent('not_present'));
});
test('projection preserves zero/false and stored hash without restoring input or cloning',()=>{const o=project(fixture());assert.equal(o.status,'partial');assert.equal(o.fields['configuration.initialCashKrw'].value,0);assert.equal(o.fields['configuration.executionPolicy.allowFractionalShares'].value,false);assert.equal(o.fields['research.configHash'].verification,'stored_observation');assert.equal(o.comparability,'unavailable');assert.equal(o.clone,'unavailable');});
test('contract-valid unavailable reasons remain distinct without defaults',()=>{for(const[key,status,reason]of [['requestedConfig','partial','not_persisted'],['configuration.initialCashKrw','partial','not_present'],['configuration.initialCashKrw','partial','invalid'],['configuration.initialCashKrw','missing','missing'],['configuration.initialCashKrw','blocked','blocked'],['configuration.initialCashKrw','limit','limit'],['configuration.initialCashKrw','ambiguous','ambiguous'],['configuration.initialCashKrw','invalid','identity_mismatch'],['batch.seed','partial','redacted_text']]){const raw=fixture();raw.status=status;raw.fields[key]=absent(reason);assert.deepEqual(project(raw).fields[key],absent(reason));}assert.deepEqual(project(fixture()).fields['configuration.executionPolicy.halfSpreadBps'],absent('invalid'));});
test('allocation daily positions require nonnegative safe integers',()=>{const key='configuration.allocationPolicy.maxNewPositionsPerDay';for(const value of [-1,0.5,Number.MAX_SAFE_INTEGER+1,Infinity,NaN,null]){const raw=fixture();raw.fields[key]=recorded(value);assert.deepEqual(project(raw).fields[key],absent('invalid'));}for(const value of [0,1,Number.MAX_SAFE_INTEGER]){const raw=fixture();raw.fields[key]=recorded(value);assert.equal(project(raw).fields[key].value,value);}});
test('recorded sources are bound to field family and unavailable fields have no source',()=>{for(const[key,value,source]of [['configuration.initialCashKrw',0,'research_manifest'],['window.startAt','2026-01-01T00:00:00Z','batch_manifest'],['research.configHash','sha256:'+'1'.repeat(64),'batch_manifest'],['research.configHash','sha256:'+'1'.repeat(64),'run_record']]){const raw=fixture();raw.fields[key]={...recorded(value),source};assert.deepEqual(project(raw).fields[key],absent('invalid'));}for(const source of ['research_manifest','run_metadata']){const raw=fixture();raw.fields['research.configHash']={...recorded('sha256:'+'1'.repeat(64)),source};assert.equal(project(raw).fields['research.configHash'].status,'recorded');}const raw=fixture();raw.fields['configuration.initialCashKrw']={...absent('missing'),source:'run_metadata'};assert.deepEqual(project(raw).fields['configuration.initialCashKrw'],absent('invalid'));});
test('field state and unavailable reason combinations match API projection',()=>{for(const[key,status,reason]of [['requestedConfig','partial','missing'],['configuration.initialCashKrw','partial','redacted_text'],['configuration.initialCashKrw','partial','identity_mismatch'],['research.configHash','partial','redacted_text'],['configuration.initialCashKrw','missing','not_present'],['configuration.initialCashKrw','blocked','missing']]){const raw=fixture();raw.status=status;raw.fields[key]=absent(reason);assert.deepEqual(project(raw).fields[key],absent('invalid'));}for(const[key,reason]of [['research.configHash','identity_mismatch'],['research.executionModelVersion','redacted_text']]){const raw=fixture();raw.fields[key]=absent(reason);assert.deepEqual(project(raw).fields[key],absent(reason));}const raw=fixture();raw.fields['configuration.initialCashKrw']={...recorded(0),reason:'missing'};assert.deepEqual(project(raw).fields['configuration.initialCashKrw'],absent('invalid'));});
test('strict envelope and exact identity reject aliases and unsupported contracts',()=>{for(const change of [{mode:'live'},{readOnly:false},{requestedRunId:'other'},{contractVersion:'future'},{clone:'available'},{comparability:'equal'},{status:{toString:null}},{fields:null}])assert.equal(project({...fixture(),...change}).status,'invalid');});
test('non-partial responses never project recorded fields as valid observations',()=>{for(const status of ['missing','invalid','blocked','limit','ambiguous']){const o=project({...fixture(),status});assert.equal(o.status,status);assert.equal(o.fields['configuration.initialCashKrw'].status,'unavailable');}});
test('extra private paths, error messages and unknown fields cannot enter display model',()=>{const raw=fixture();raw.error='SYNTHETIC_PRIVATE';raw.fields['secret.path']=recorded('/home/SYNTHETIC_PRIVATE');raw.fields['configuration.initialCashKrw']=recorded('/home/SYNTHETIC_PRIVATE');assert.doesNotMatch(JSON.stringify(project(raw)),/SYNTHETIC_PRIVATE|secret\.path|\/home/);});
test('recorded free seed, original input and runtime claims are unavailable',()=>{for(const key of ['batch.seed','child.runSeed','window.seed','requestedConfig','effectiveConfig','notices','runtime.gitRevision','runtime.dependencyLockHash','runtime.nodeVersion']){const raw=fixture();raw.fields[key]=recorded('SYNTHETIC_PRIVATE');assert.deepEqual(project(raw).fields[key],absent('invalid'));assert.doesNotMatch(JSON.stringify(project(raw)),/SYNTHETIC_PRIVATE/);}});
test('all six date fields reject permissive Date.parse private comments',()=>{for(const key of ['window.startAt','window.endAt','window.rangeStart','window.rangeEnd','configuration.clock.startAt','configuration.clock.endAt']){const raw=fixture();raw.fields[key]=recorded('2026-01-01 (/home/synthetic_private/token.txt)');assert.deepEqual(project(raw).fields[key],absent('invalid'));assert.doesNotMatch(JSON.stringify(project(raw)),/synthetic_private|token\.txt/);}});
test('calendar-invalid dates are not normalized into stored observations',()=>{for(const date of ['2026-02-31T00:00:00Z','2026-01-01T24:00:00Z','2026-01-01','2026-01-01T00:00:00Z (private)'])assert.equal(strictTimestamp(date),false);assert.equal(strictTimestamp('2024-02-29T00:00:00+09:00'),true);});
test('malformed enums, hashes, collections and field status do not leak arbitrary strings',()=>{for(const[key,value]of [['research.configHash','token'],['research.executionModelVersion','/home/private'],['configuration.riskProfile','private'],['configuration.constraints.allowedActions',Array.from({length:17},()=>0)],['configuration.executionPolicy.allowFractionalShares','secret']]){const raw=fixture();raw.fields[key]=recorded(value);assert.equal(project(raw).fields[key].status,'unavailable');}});
test('nullable, numeric bounds and action enums match stored field types',()=>{
  for(const[key,value]of [['configuration.initialCashKrw',null],['configuration.initialCashKrw',-1],['configuration.clock.stepSeconds',0],['configuration.riskPolicy.minCashReserveRatio',2],['configuration.paperExitPolicy.stopLossRatio',0],['window.startAt',null],['configuration.constraints.allowedActions',['NO_ACTION']]]){const raw=fixture();raw.fields[key]=recorded(value);assert.equal(project(raw).fields[key].status,'unavailable');}
  const raw=fixture();raw.fields['window.rangeStart']=recorded(null);raw.fields['configuration.riskProfile']=recorded('aggressive_paper');assert.equal(project(raw).fields['window.rangeStart'].status,'recorded');assert.equal(project(raw).fields['configuration.riskProfile'].value,'aggressive_paper');
});
test('invalid requested identity makes no network request',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);global.fetch=async()=>{throw Error('must not fetch');};assert.equal((await readRunProvenance('../child')).status,'invalid');});
test('reader performs exactly one no-store GET and preserves requested identity',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(fixture()));};assert.equal((await readRunProvenance('child')).status,'partial');assert.equal(calls.length,1);assert.match(calls[0].url,/\/batch\/replay\/runs\/provenance\?runId=child$/);assert.equal(calls[0].options.method,'GET');assert.equal(calls[0].options.cache,'no-store');});
test('HTTP/parse/errors isolate observation and do not reveal exception bodies',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);for(const response of [new Response('{}',{status:503}),new Response('{',{status:200})]){global.fetch=async()=>response;assert.equal((await readRunProvenance('child')).status,'offline');}global.fetch=async()=>{throw Error('PRIVATE_TOKEN');};assert.doesNotMatch(JSON.stringify(await readRunProvenance('child')),/PRIVATE_TOKEN/);});
test('one two-second abort terminates stalled read without retries',async t=>{const original=global.fetch;t.after(()=>global.fetch=original);let calls=0,signal;global.fetch=async(_url,options)=>{calls++;signal=options.signal;return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted'))));};assert.equal((await readRunProvenance('child')).status,'offline');assert.equal(signal.aborted,true);assert.equal(calls,1);});
