import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
import { test } from 'node:test';
const source=await readFile(new URL('../src/lib/runWorkspace.ts',import.meta.url),'utf8');
const {runWorkspaceState,readRunWorkspaceTab,isRunSnapshot,validRunLookupId,createRunRefresh}=await import('data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(source)));
const stamp='2026-10-04T00:00:00.000Z';
function fixture(status='running') { return {apiBaseLabel:'fixture',fetchedAt:stamp,runDetail:{status:'ok',endpoint:'/batch/replay/runs',fetchedAt:stamp,data:{mode:'paper_only',readOnly:true,requestedId:'batch-fixture',runId:'child-fixture',batchId:'batch-fixture',batchStatus:status,endpointStatus:'ok',sourceRunsPath:null,latestArtifactsRunId:'child-fixture',warnings:[],status:'ok',runSource:status==='active'?'legacy_active':status==='running'?'active_manifest':'persisted',simulationObservation:{status:'not_requested'},run:{runId:'child-fixture',batchId:'batch-fixture',status,startedAt:stamp,completedAt:null,failedAt:null,skippedAt:null,marketRegimeLabel:null,storageBaseDir:null,reportPath:null,error:null,skipReason:null,runIndex:0,totalReturnRatio:0,finalVirtualNetWorthKrw:0,tradeCount:0,rejectedCount:0,aiDecisionFailureCount:0},artifacts:{runId:'child-fixture',status:'ok',runStatus:status,reportTitle:null,progressStatusLabel:null,simulatedAt:null,completedTickCount:0,tickCount:0,rejectedCount:0,currentVirtualNetWorthKrw:0,currentCashKrw:0,currentPositionCount:0,decisionCount:0,totalDecisionCount:0,riskDecisionCount:0,totalRiskDecisionCount:0,tradeCount:0,totalTradeCount:0,reportStatus:'ok',progressStatus:'ok',decisionsStatus:'ok',riskDecisionsStatus:'ok',tradesStatus:'ok'}}}}; }
test('URL view accepts record and safely defaults unsupported tabs',()=>{ assert.equal(readRunWorkspaceTab('record'),'record');for(const value of ['replay','evidence','bogus',null])assert.equal(readRunWorkspaceTab(value),'summary'); });
test('terminal child results stop polling without equating completion and success',()=>{for(const status of ['completed','completed_with_failures','failed','skipped'])assert.deepEqual(runWorkspaceState(fixture(status).runDetail),{poll:false,completeness:'complete',execution:status});});
test('running is observed separately from batch and endpoint source',()=>{const p=fixture();p.runDetail.data.batchStatus='completed_with_failures';p.runDetail.data.endpointStatus='degraded';assert.equal(runWorkspaceState(p.runDetail).execution,'running');assert.equal(runWorkspaceState(p.runDetail).poll,true);});
test('accepted-only unknown polls but runner failure or missing observation does not',()=>{const p=fixture();p.runDetail.data.run=null;p.runDetail.data.artifacts=null;p.runDetail.data.simulationObservation={status:'available',outcome:'unknown'};assert.deepEqual(runWorkspaceState(p.runDetail),{poll:true,completeness:'missing',execution:'unknown'});p.runDetail.data.simulationObservation.outcome='runner_failed';assert.equal(runWorkspaceState(p.runDetail).poll,false);p.runDetail.data.simulationObservation={status:'missing'};assert.equal(runWorkspaceState(p.runDetail).poll,false);});
test('batch runner failure cannot overwrite a terminal child result',()=>{const p=fixture('completed_with_failures');p.runDetail.data.simulationObservation={status:'available',outcome:'runner_failed'};assert.equal(runWorkspaceState(p.runDetail).execution,'completed_with_failures');});
test('artifact read damage stays partial and mismatched child is unavailable',()=>{for(const status of ['missing','corrupt','degraded','blocked','invalid']){const p=fixture('completed');p.runDetail.data.artifacts.reportStatus=status;assert.equal(runWorkspaceState(p.runDetail).completeness,'partial');}const p=fixture();p.runDetail.data.artifacts.runId='other-child';assert.equal(runWorkspaceState(p.runDetail).completeness,'missing');});
test('wrapper offline/invalid do not fabricate child failure',()=>{for(const status of ['offline','invalid'])assert.deepEqual(runWorkspaceState({status,data:null}),{poll:false,completeness:'unavailable',execution:'unknown'});});
test('snapshot transport identity and lookup guards fail closed',()=>{const p=fixture();assert.equal(isRunSnapshot(p,'batch-fixture'),true);assert.equal(isRunSnapshot(p,'other-batch'),false);assert.equal(isRunSnapshot(null,'batch-fixture'),false);p.runDetail.data.artifacts.runId='other-child';assert.equal(isRunSnapshot(p,'batch-fixture'),false);for(const value of ['','../escape','a\\b','a\n','x'.repeat(257)])assert.equal(validRunLookupId(value),false);assert.equal(validRunLookupId('legacy fixture ID'),true);});
test('transport rejects malformed nested metrics, read statuses and observations but retains genuine zeros',()=>{assert.equal(isRunSnapshot(fixture(),'batch-fixture'),true);for(const mutate of [p=>p.runDetail.data.run.tradeCount='0',p=>p.runDetail.data.artifacts.reportStatus='invented',p=>p.runDetail.data.artifacts.totalTradeCount=null,p=>p.runDetail.data.simulationObservation={status:'available',simulationRunId:'other-batch',acceptedAt:stamp,outcome:'unknown',runnerFailure:null}]){const p=fixture();mutate(p);assert.equal(isRunSnapshot(p,'batch-fixture'),false);}});
function harness(read,initial=fixture()) {
  const timers=new Map(), applied=[],states=[];let next=1,errors=0;
  const lifecycle=createRunRefresh({initial,read,apply:p=>applied.push(p),state:s=>states.push(s),error:()=>errors++,schedule:f=>{const id=next++;timers.set(id,f);return id;},cancel:id=>timers.delete(id)});
  return {lifecycle,timers,applied,states,get errors(){return errors;},async tick(){assert.equal(timers.size,1);const [id,f]=timers.entries().next().value;timers.delete(id);f();await new Promise(resolve=>setImmediate(resolve));}};
}
test('automatic GET is single-flight and terminal response clears schedule',async()=>{let resolve,reads=0;const h=harness(()=>{reads++;return new Promise(r=>resolve=r);});await h.tick();await h.lifecycle.refresh();assert.equal(reads,1);assert.equal(h.timers.size,0);resolve(fixture('completed'));await new Promise(r=>setImmediate(r));assert.equal(h.applied.length,1);assert.equal(h.timers.size,0);assert.equal(h.states.at(-1).busy,false);h.lifecycle.dispose();});
test('automatic observation has a hard visit limit while manual GET stays available',async()=>{let reads=0;const h=harness(async()=>{reads++;return fixture();});for(let i=0;i<12;i++)await h.tick();assert.equal(reads,12);assert.equal(h.timers.size,0);assert.equal(h.states.at(-1).limited,true);await h.lifecycle.refresh();assert.equal(reads,13);assert.equal(h.timers.size,0);h.lifecycle.dispose();});
test('dispose aborts request and discards late response even if fetch ignores signal',async()=>{let resolve,signal;const h=harness(s=>{signal=s;return new Promise(r=>resolve=r);});await h.tick();h.lifecycle.dispose();assert.equal(signal.aborted,true);resolve(fixture('completed'));await new Promise(r=>setImmediate(r));assert.equal(h.applied.length,0);assert.equal(h.timers.size,0);});
test('hidden document clears timer and rejects stale request before resuming',async()=>{let resolve,signal;const h=harness(s=>{signal=s;return new Promise(r=>resolve=r);});await h.tick();h.lifecycle.setVisible(false);assert.equal(signal.aborted,true);h.lifecycle.setVisible(true);assert.equal(h.timers.size,1);resolve(fixture('completed'));await new Promise(r=>setImmediate(r));assert.equal(h.applied.length,0);h.lifecycle.dispose();assert.equal(h.timers.size,0);});
test('transport failure stops auto polling until explicit successful GET',async()=>{let fail=true;const h=harness(async()=>{if(fail)throw Error('offline');return fixture();});await h.tick();assert.equal(h.errors,1);assert.equal(h.timers.size,0);fail=false;await h.lifecycle.refresh();assert.equal(h.applied.length,1);assert.equal(h.timers.size,1);h.lifecycle.dispose();});
test('invalid/offline returned snapshots and terminal initial state schedule nothing',async()=>{for(const status of ['offline','invalid']){const p=fixture();p.runDetail={status,data:null};const h=harness(async()=>p);await h.tick();assert.equal(h.timers.size,0);h.lifecycle.dispose();}const h=harness(async()=>fixture(),fixture('completed'));assert.equal(h.timers.size,0);h.lifecycle.dispose();});

test('legacy active accepts only bound child or batch identity and never becomes automatic running',()=>{
  const p=fixture('active');assert.equal(isRunSnapshot(p,'batch-fixture'),true);assert.equal(runWorkspaceState(p.runDetail).execution,'active');assert.equal(runWorkspaceState(p.runDetail).poll,false);
  for(const mutate of [p=>p.runDetail.data.run.status='invented',p=>p.runDetail.data.run.runId='',p=>{p.runDetail.data.run.runId='other-child';p.runDetail.data.runId='other-child';p.runDetail.data.run.batchId='other-batch';},p=>p.runDetail.data.run.completedAt=stamp,p=>p.runDetail.data.artifacts.runId='other-child']){const value=fixture('active');mutate(value);assert.equal(isRunSnapshot(value,'batch-fixture'),false);}
});
test('active normalizer never borrows child identity or status from another artifact',async t=>{
  const saved=process.env.DASHBOARD_OPS_API_BASE_URL;process.env.DASHBOARD_OPS_API_BASE_URL='http://active.test';t.after(()=>{if(saved===undefined)delete process.env.DASHBOARD_OPS_API_BASE_URL;else process.env.DASHBOARD_OPS_API_BASE_URL=saved;});
  const model=await import('data:text/javascript,'+encodeURIComponent(stripTypeScriptTypes(await readFile(new URL('../src/lib/dashboardViewModels.ts',import.meta.url),'utf8'))));
  let activeRun={runId:'child-fixture'},artifacts={runId:'other-child',runStatus:'completed',status:'ok',reportStatus:'missing',progressStatus:'missing',decisionsStatus:'missing',riskDecisionsStatus:'missing',tradesStatus:'missing'};
  t.mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({mode:'paper_only',readOnly:true,status:'ok',batchId:'batch-fixture',batchStatus:'unknown',runs:[],selectedRun:null,activeRun,latestRunArtifacts:artifacts}),{status:200,headers:{'content-type':'application/json'}}));
  const bound=await model.readRunDetailPageData('child-fixture');assert.equal(bound.runDetail.data.run.status,'active');assert.equal(bound.runDetail.data.artifacts,null);assert.equal(isRunSnapshot(bound,'child-fixture'),true);assert.equal(runWorkspaceState(bound.runDetail).poll,false);
  for(const identity of [{}, {runId:''}, {runId:'   '}]){activeRun=identity;const missing=await model.readRunDetailPageData('batch-fixture');assert.equal(missing.runDetail.data.run,null);assert.equal(missing.runDetail.data.artifacts,null);assert.equal(missing.runDetail.data.status,'missing');assert.equal(isRunSnapshot(missing,'batch-fixture'),true);}
});
